# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-04 23:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Atender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirma', models.BooleanField(verbose_name='Confirma')),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128)),
                ('chefe', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128)),
                ('cpf', models.CharField(max_length=14)),
                ('departamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trasladoApp.Departamento')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Motorista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128)),
                ('cnh', models.CharField(max_length=20)),
                ('cpf', models.CharField(max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='Solicitar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataHora', models.DateTimeField(blank=True, null=True)),
                ('origem', models.CharField(max_length=128)),
                ('destino', models.CharField(max_length=128)),
                ('departamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trasladoApp.Departamento')),
                ('funcionarios', models.ManyToManyField(blank=True, null=True, to='trasladoApp.Funcionario')),
            ],
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=20)),
                ('modelo', models.CharField(max_length=10)),
                ('ano', models.CharField(max_length=4)),
                ('marca', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='atender',
            name='motorista',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trasladoApp.Motorista'),
        ),
        migrations.AddField(
            model_name='atender',
            name='solicitacao',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='trasladoApp.Solicitar'),
        ),
        migrations.AddField(
            model_name='atender',
            name='veiculo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trasladoApp.Veiculo'),
        ),
    ]
